set arduino_board_desc=Arduino Uno
set arduino_board_name=uno
set arduino_build_mcu=atmega328p
set arduino_build_f_cpu=16000000L
set arduino_build_core=arduino
set arduino_upload_protocol=stk500
set arduino_upload_speed=115200
set arduino_upload_maximum_size=32256
set arduino_upload_port=
set arduino_core_full_path=C:\Dev\Projects\Home\arduino-0022\hardware\arduino\cores\arduino
set arduino_project_full_path=C:\Dev\Projects\Home\Arduino\SecretKnockLock
set avr_bin_path=C:\Dev\Projects\Home\arduino-0022\hardware\tools\avr\bin
set avr_etc_path=c:\dev\projects\home\arduino-0022\hardware\tools\avr\etc
set arduino_compiler_include_paths= -IC:\Dev\Projects\Home\arduino-0022\hardware\arduino\cores\arduino -Ic:\dev\projects\home\arduino-0022\hardware\tools\avr\avr\include\avr
set vm_do_compile=1
set vm_do_upload=0
